name: CI - Payment Service

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql_payments:
        image: mysql:8.4.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: labo05_payments_db
          MYSQL_USER: labo05
          MYSQL_PASSWORD: labo05
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Créer le fichier .env (CI pointe vers le service localhost)
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo05_payments_db" >> .env
          echo "DB_USER=labo05" >> .env
          echo "DB_PASSWORD=labo05" >> .env

      - name: Charger le schéma et les données seed dans MySQL
        run: mysql -h 127.0.0.1 -u root -proot < db-init/init.sql

      - name: Run tests (pytest)
        working-directory: src
        run: pytest -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build de l'image Docker (conteneurisation)
        run: docker build -t payments-api:${{ github.sha }} .
